---


- name: create pipeline
  k8s:
    state: present
    kind: Pipeline
    api_version: tekton.dev/v1
    definition:
      metadata:
        name: demo-pipeline
        namespace: quarkus-tcc-demo
      spec:
        tasks:
          - name: test-quarkus-app
            taskRef:
              kind: Task
              name: build-app

- name: wait a minute and let the Pipeline become ready
  pause:
      minutes: 1

- name: create task
  k8s:
    state: present
    kind: Task
    api_version: tekton.dev/v1beta1
    definition:
      metadata:
          name: build-app
          namespace: quarkus-tcc-demo
      spec:
          steps:
              - name: build
                image: "docker.io/sergeiegorov446/build-image-java:latest"
                workingDir: /workspace
                env:
                    - name: TC_CLOUD_TOKEN
                      value: "{{ cloud_token }}"
                    - name: TC_CLOUD_ENDPOINT
                      value: "https://eks-us.workloads.testcontainers.cloud/lease?zone={{ client_id }}-{{ zone_name }}"
                script: |
                    set -x
                    git clone https://github.com/danieloh30/quarkus-tcc-os-demo.git
                    cd quarkus-tcc-os-demo
                    sh -c "$(curl -fsSL https://get.testcontainers.cloud/bash)"
                    ./mvnw --no-transfer-progress -B verify

