---
# Setup OpenShift Pipelines via operator
- name: Create OpenShift Objects for pipelines
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/pipelines_subscription.yaml

- name: wait a minute and let the Pipelines CRD become ready
  pause:
      minutes: 1

# # wait for CRD to be a thing
- name: Wait for Pipelines CRD to be ready
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: pipelines.tekton.dev
  register: r_pipeline_crd
  retries: 200
  delay: 20
  until: r_pipeline_crd.resources | list | length == 1