---

# deploy test containers operator
- name: Create operator subscription for test containers
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/tcc_subscription.yaml

- name: wait a minute and let the tcc CRD become ready
  pause:
      minutes: 1

# # wait for CRD to be a thing
- name: Wait for tcc CRD to be ready
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: tcczones.dataplane.testcontainers.cloud
  register: r_tcc_crd
  retries: 200
  delay: 20
  until: r_tcc_crd.resources | list | length == 1

- name: create test containers zone
  k8s:
    state: present
    kind: Zone
    api_version: dataplane.testcontainers.cloud/v1alpha1
    definition:
      metadata:
        name: "{{ zone_name }}"
        namespace: "quarkus-tcc-demo"
      spec:
        clientId: "{{ client_id }}"
        clientSecret: "{{ client_secret }}"
        pullSecret: "{{ pull_secret }}"