---
- name: Verify everything is deployed correctly
  include_tasks: verify-workload.yaml



- name: output workshop info
  agnosticd_user_info:
    msg: |
      Update local Test Containers desktop with 'echo "cloud.endpoint=https://eks-us.workloads.testcontainers.cloud/lease?zone={{ client_id }}-{{ zone_name }}" > ~/.config/testcontainers/cloud.properties'
      You will need to restart Test Containers Dekstop.

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  agnosticd_user_info:
    msg: |
      Post-Workload Tasks completed successfully.
  when: not silent|bool
