---
- name: Verify everything is deployed correctly
  include_tasks: verify-workload.yaml



- name: output workshop info
  agnosticd_user_info:
    msg: |
      [Instructor Only] Admin login with 'admin' / '{{ workshop_openshift_user_password }}'
    


# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  agnosticd_user_info:
    msg: |
      Post-Workload Tasks completed successfully.
  when: not silent|bool
