# vim: set ft=ansible
---
# Implement your Workload removal tasks here

- name: remove the pipelines CR
  k8s:
    state: absent
    name: demo-pipeline
    kind: Pipeline
    api_version: tekton.dev/v1
    namespace: quarkus-tcc-demo

- name: remove the task CR
  k8s:
    state: absent
    name: build-app
    kind: Task
    api_version: tekton.dev/v1beta1
    namespace: quarkus-tcc-demo

- name: remove the tcc CR
  k8s:
    state: absent
    name: "{{ zone_name }}"
    kind: Zone
    api_version: dataplane.testcontainers.cloud/v1alpha1
    namespace: quarkus-tcc-demo

- name: remove the quarkus-tcc-demo project
  k8s:
    state: absent
    name: quarkus-tcc-demo
    kind: Project
    api_version: project.openshift.io/v1


- name: Remove operator subscription for openshift-pipelines-operator
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: openshift-operators
    name: openshift-pipelines-operator-rh

- name: Remove operator subscription for tcc-operator
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: openshift-operators
    name: tcc-operator

- name: Remove operator subscription for kubevirt-hyperconverged
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: openshift-cnv
    name: kubevirt-hyperconverged

- name: remove the hyperverged CR
  k8s:
    state: absent
    name: kubevirt-hyperconverged
    kind: HyperConverged
    api_version: hco.kubevirt.io/v1beta1
    namespace: openshift-cnv

- name: remove the openshift-cnv project
  k8s:
    state: absent
    name: openshift-cnv
    kind: Project
    api_version: project.openshift.io/v1

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
