---

- name: verify tcc pod are running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: quarkus-tcc-demo
    label_selectors:
      - app.kubernetes.io/name=tcc-zone
    field_selectors:
      - status.phase=Running
  register: r_tcc_pod
  retries: 200
  delay: 20
  until: r_tcc_pod.resources | list | length == 1

- name: verify tcc vm pods are running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: quarkus-tcc-demo
    label_selectors:
      - tcc/zone={{ zone_name }}
    field_selectors:
      - status.phase=Running
  register: r_vm_pod
  retries: 200
  delay: 20
  until: r_vm_pod.resources | list | length == 5

# Leave this as the last task in the playbook.
- name: workload verification tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool