---
become_override: False
ocp_username: opentlc-mgr
silent: False

num_users: 1
workshop_openshift_user_name: userXX
workshop_openshift_user_password: 'openshift'
workshop_che_user_name: userXX
workshop_che_user_password: 'openshift'
workshop_openshift_admin_password: 'r3dh4t1!'
workshop_rhsso_admin_user_name: admin
workshop_rhsso_admin_password: 'r3dh4t1!'

module_type: m1

#
# All modules. Do NOT use a comma (,) in the titles or paths!
#
module_titles:
  - { name: m1, title: "JBoss 7 to JBoss 8 Migration workshop", path: /workshop/EAP8-lab/lab/intro }
