---
# External role to setup grader host virtualenv and FTL grading infra
roles:
- name: ftl-injector
  src: https://github.com/redhat-gpte-devopsautomation/ftl-injector
  version: v0.17

collections:
- name: amazon.aws
  version: 2.2.0
