---

- name: Setup remainin pre-requisite gitops roles
  include_role:
    name: ocp4_workload_kubevirt

# - name: create project for virt
#   k8s:
#     state: present
#     kind: Project
#     api_version: project.openshift.io/v1
#     definition:
#       metadata:
#         name: "openshift-cnv"
#         annotations:
#           openshift.io/description: ""
#           openshift.io/display-name: "OCP virt"


# - name: create project for virt
#   k8s:
#     state: present
#     kind: OperatorGroup
#     api_version: operators.coreos.com/v1
#     definition:
#       metadata:
#         name: ocp-virt
#         namespace: openshift-cnv
#       spec:
#         targetNamespaces:
#         - openshift-cnv

# # Setup OpenShift virt via operator
# - name: Create OpenShift Objects for virt
#   k8s:
#     state: present
#     merge_type:
#     - strategic-merge
#     - merge
#     definition: "{{ lookup('file', item ) | from_yaml }}"
#   loop:
#   - ./files/virt_subscription.yaml

# - name: wait 2 minutes and let the hyperconverged CRD become ready
#   pause:
#       minutes: 2

# # # wait for CRD to be a thing
# - name: Wait for hyperconverged CRD to be ready
#   k8s_info:
#     api_version: apiextensions.k8s.io/v1
#     kind: CustomResourceDefinition
#     name: hyperconvergeds.hco.kubevirt.io
#   register: r_hyp_crd
#   retries: 200
#   delay: 20
#   until: r_hyp_crd.resources | list | length == 1

# # Setup OpenShift virt via operator
# - name: Create HyperConverged instance
#   k8s:
#     state: present
#     merge_type:
#     - strategic-merge
#     - merge
#     definition: "{{ lookup('file', item ) | from_yaml }}"
#   loop:
#   - ./files/hyper-converged.yaml

