---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/tcc-operator.openshift-operators: ''
  name: tcc-operator
  namespace: openshift-operators
spec:
  channel: preview
  installPlanApproval: Automatic
  name: tcc-operator
  source: docker
  sourceNamespace: openshift-marketplace
  startingCSV: "{{ ocp4_workload_testcontainers_tcc_operator_starting_csv }}"
